CREATE TABLE CONFIG (
    CONFIG_KEY TEXT NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    PRIMARY KEY (CONFIG_KEY, CONFIG_VALUE)
);

CREATE TABLE REACTIONS (
    REACTION_TEXT TEXT NOT NULL,
    REACTION_IMAGE_URL TEXT NOT NULL,
    PRIMARY KEY (REACTION_TEXT, REACTION_IMAGE_URL)
);

CREATE TABLE CLOCKIN (
    USER_ID TEXT NOT NULL PRIMARY KEY,
    TIMES_CLOCKED_IN INT NOT NULL,
    LAST_TIME TEXT NOT NULL
);

CREATE TABLE ADMINS (
    USER_ID TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE HOLOLIVE_MEMBERS (
    ID          INTEGER PRIMARY KEY,
    NAME        TEXT NOT NULL,
    CREATED_AT  TEXT NOT NULL,
    UPDATED_AT  TEXT NOT NULL,
    AVATAR      TEXT NOT NULL,
    COLOR_MAIN  TEXT NOT NULL,
    COLOR_SUB   TEXT NOT NULL,
    GRADUATED   INTEGER
);

CREATE TABLE HOLOLIVE_CHANNELS (
    ID          INTEGER PRIMARY KEY,
    CHANNEL     TEXT NOT NULL,
    PLATFORM_ID INTEGER NOT NULL,
    MEMBER_ID   INTEGER NOT NULL,
    EDITOR_ID   INTEGER,
    CREATED_AT  TEXT NOT NULL,
    UPDATED_AT  TEXT NOT NULL
);